purbeurre/products/urls.py
# from django.conf.urls import url

from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [

     path('search/', views.SearchView.as_view(), name='search'),
     path('<int:product_id>/result/', views.ResultView.as_view(), name='result'),
     path('save/', views.SaveView, name='save'),
     path('delete/<int:pk>', views.DeleteSubstituteView.as_view(), name='delete'),
     path('<int:pk>/detail/', views.DetailProductView.as_view(), name='detail'),
     path('myproducts/', views.MyProductsView.as_view(), name='myproducts'),
]

purbeurre/purbeurre/urls.py
from django.contrib import admin
from django.urls import path
# from django.conf import settings
from django.urls import include  # For django versions from 2.0 and up

from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('legal', TemplateView.as_view(template_name='legal.html'), name='legal'),
    path('products/', include('products.urls')),
    path('accounts/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

purbeurre/products/models.py
from django.db import models
# from django.contrib.auth.models import User
from purbeurre import settings

# Create your models here.


class Product(models.Model):
    """Product model."""
    product_name = models.CharField(max_length=200)
    nutrition_grades = models.CharField(max_length=1)
    fat = models.CharField(max_length=8)
    fat_100g = models.DecimalField(max_digits=3, decimal_places=1)
    saturated_fat = models.CharField(max_length=8)
    saturated_fat_100g = models.DecimalField(max_digits=3, decimal_places=1)
    sugars = models.CharField(max_length=8)
    sugars_100g = models.DecimalField(max_digits=3, decimal_places=1)
    salt = models.CharField(max_length=8)
    salt_100g = models.DecimalField(max_digits=3, decimal_places=1)
    image_url = models.URLField()
    url = models.URLField()
    category = models.CharField(max_length=20)
    last_modified_t = models.IntegerField(default=0)
    id_off = models.CharField(max_length=20)

    def __str__(self):
        return self.product_name


class Substitute(models.Model):
    """Substitute model."""
    product_id = models.ForeignKey(
        Product, related_name='product', on_delete=models.CASCADE)
    substitute_id = models.ForeignKey(
        Product, related_name='substitute', on_delete=models.CASCADE)
    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('product_id', 'substitute_id', 'user_id'),)

purbeurre/products/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, DeleteView

from sentry_sdk import capture_message, configure_scope

from authentication.models import User
from .models import Product, Substitute
# Create your views here.


class SearchView(ListView):
    """Return products from DB from query."""
    template_name = 'products/search.html'
    paginate_by = 9

    def get_queryset(self):
        with configure_scope() as scope:
            if '_auth_user_id' in self.request.session._session:
                scope.user = {
                    "email": User.objects.get(pk=self.request.session._session['_auth_user_id']).email
                }
            scope.level = 'info'
            capture_message('New search')

        return Product.objects.filter(
            product_name__icontains=self.request.GET['query']).order_by('product_name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.GET['query']
        context['target'] = 'products:result'
        context['query'] = self.request.GET['query']
        return context


class ResultView(ListView):
    """Return substitutes with same category and better/equal nutrigrade."""
    template_name = 'products/result.html'

    def get_queryset(self):
        self.product = Product.objects.get(pk=self.kwargs['product_id'])
        return Product.objects\
            .filter(category=self.product.category)\
            .filter(nutrition_grades__lte=self.product.nutrition_grades)\
            .exclude(id=self.kwargs['product_id'])\
            .order_by('nutrition_grades')[:9]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'allreadysaved' in self.request.GET:
            context['message'] = 'Déjà enregistré'
        context['query'] = self.product.product_name
        context['product'] = self.product
        context['title'] = self.product
        context['target'] = 'products:detail'
        return context


class DetailProductView(DetailView):
    """Show product details."""
    template_name = 'products/detail.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = kwargs['object'].product_name
        return context


class MyProductsView(LoginRequiredMixin, ListView):
    """Show saved products."""
    template_name = 'products/myproducts.html'
    paginate_by = 5

    def get_queryset(self):
        return Substitute.objects.filter(
            user_id=self.request.user.id).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mes produits'
        context['target'] = 'products:result'
        return context


class DeleteSubstituteView(LoginRequiredMixin, DeleteView):
    """Ask for delete saved product."""
    model = Substitute
    success_url = reverse_lazy('products:myproducts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mes produits'
        return context


# @login_required
def SaveView(request):
    """Save product/substitute."""
    if request.method == 'POST':
        # get data from POST
        next_url = request.POST['next']
        product_id = request.POST['product_id']
        substitute_id = request.POST['substitute_id']
        if request.user.id:
            # get data from DB
            product_obj = Product.objects.get(pk=product_id)
            substitute_obj = Product.objects.get(pk=substitute_id)
            user_obj = User.objects.get(pk=request.user.id)
            # test if all obj are sets
            if product_obj and substitute_obj and user_obj:
                # create Substitute or return "allreadysaved"
                obj, created = Substitute.objects.get_or_create(
                    user_id=user_obj,
                    product_id=product_obj,
                    substitute_id=substitute_obj
                    )
                if created:
                    return redirect('products:myproducts')
                else:
                    return redirect(next_url+"?allreadysaved")
        else:
            request.session['keep_substitute'] = (product_id, substitute_id)
            return redirect('authentication:login')

    # if user was not connected, keep_substitue is in session
    elif 'keep_substitute' in request.session.keys():
        (product_id, substitute_id) = request.session['keep_substitute']
        del request.session['keep_substitute']
        if request.user.id:
            # get data from DB
            product_obj = Product.objects.get(pk=product_id)
            substitute_obj = Product.objects.get(pk=substitute_id)
            user_obj = User.objects.get(pk=request.user.id)
            # test if all obj are sets
            if product_obj and substitute_obj and user_obj:
                # create Substitute or return "allreadysaved"
                obj, created = Substitute.objects.get_or_create(
                    user_id=user_obj,
                    product_id=product_obj,
                    substitute_id=substitute_obj
                    )
                return redirect('products:myproducts')
    return redirect('index')

purbeurre/products/templates/products/__base_product_result.html
  <!-- Product Result Section -->
  <section id="product-result">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-12 text-center">
          <h2>Vous pouvez remplacer cet aliment par : </h2>
        </div>
        {% for product in result %}
          <div class="col-12 col-lg-4">
            <div class="product-thumb">
              <div class="nutriscore nutriscore-{{product.nutrition_grades|upper}} text-center"></div>
                <a href="{% url target product.id %}">
                  <img src="{{product.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
              <p class="text-center">{{product|title}}</p>
              <p class="text-center"><i class="fas fa-save fa-1x"></i> Sauvegarder</p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
</section>

purbeurre/products/templates/products/base_product_title_img.html
    <!-- Product Search Section -->
    <header id="product-search" class="bg-product-search">
        <div class="container-fluid h-200">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <!-- <img src="{#product.image_url#}" alt=""> -->
            <h1 class="text-white font-weight-bold">{{ query|title }}</h1>
        </div>
        </div>
    </header>
    
    <!-- Modify product picture -->
    <style>
    .bg-product-search {
        padding-top: 10rem;
        background-color: #345A61;
        background: linear-gradient(to bottom,rgba(92,77,66,.8) 0,rgba(92,77,66,.8) 100%),
            url({{product.image_url}});
        background-repeat: no-repeat;
        background-position-x: 35%;
        background-position-y: 50%;
    }
    </style>

purbeurre/products/templates/products/detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% include 'products/base_product_title_img.html' %}

  <!-- Product Details -->
  <section id="product-detail">
    <div class="container">
      <div class="row align-items-center justify-content-center py-3 mx-1">
        <div class="col-12 col-lg-6 text-center">
          <img src="{% static 'img/nutricode/nutriscore-'|add:product.nutrition_grades|add:'.svg' %}" alt="">
        </div>
        <div class="col-12 col-lg-6">
          <h3>Repères nutritionnels pour 100 g</h3>
          <ul class="nutrient-levels">
            <li class="{{ product.fat }}">{{ product.fat_100g }} g Matières grasses / Lipides</li>
            <li class="{{ product.saturated_fat }}">{{ product.saturated_fat_100g }} g Acides gras saturés</li>
            <li class="{{ product.sugars }}">{{ product.sugars_100g }} g Sucres</li>
            <li class="{{ product.salt }}">{{ product.salt_100g }} g Sel</li>
          </ul>
        </div>
        <div class="col-12 text-center">
          <a href="{{product.url}}" target="_blank">
            <button type="button" class="btn btn-lg btn-outline-secondary">Voir la fiche Openfoodfacts</button>
          </a>
        </div>
        <div class="col-12 text-center">
          <button onclick="window.history.back();" type="button" class="btn btn-lg btn-outline-secondary mt-0">Retour</button>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

purbeurre/products/templates/products/myproducts.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% include 'base_title_section.html' %}
  
  <!-- My Product Result Section -->
  <section id="product-result">
    <div class="container">
        {% if not object_list %}
        <div class="row align-items-center justify-content-center"></div>
          <div class="alert alert-warning">Il n'y a pas de produits enregistrés</div>
        </div>
        {% endif %}
        {% for sl in object_list %}
        <div class="row align-items-center justify-content-center">
          <div class="col-4 mx-1 px-0">
            <div class="product-thumb-myproduct">
              <div class="nutriscore nutriscore-{{sl.product_id.nutrition_grades|upper}} text-center"></div>
              <a href="{% url 'products:detail' sl.product_id.id %}">
                <img src="{{sl.product_id.image_url}}" class="rounded mx-auto d-block" alt="">
              </a>
              <div class="product-thumb-legend">
                <p class="text-center">{{sl.product_id|title}}</p>
              </div>
            </div>
          </div>
          <div class="col-1 px-0 text-center">
            <i class="fas fa-arrow-right"></i>
          </div>
          <div class="col-4 mx-1 px-0">
            <div class="product-thumb-myproduct">
              <div class="nutriscore nutriscore-{{sl.substitute_id.nutrition_grades|upper}} text-center"></div>
                <a href="{% url 'products:detail' sl.substitute_id.id %}">
                  <img src="{{sl.substitute_id.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
              <div class="product-thumb-legend">
                <p class="text-center">{{sl.substitute_id|title}}</p>
              </div>
            </div>
          </div>
          <div class="col-1 px-0">
            <p>
              <form action="{% url 'products:delete' sl.id %}" method="GET">
                {% csrf_token %}
                <button type="submit" class="btn btn-link"><i class="fas fa-trash-alt"></i></button>
              </form>
            </p>
          </div>
        </div>
        {% endfor %}
        {% if is_paginated %}
        <div class="row align-items-center justify-content-center">
          <div class="pagination text-center">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="?page={{ page_obj.previous_page_number }}">Précédente</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="?page={{ page_obj.next_page_number }}">Suivante</a>
                  {% endif %}
              </span>
          </div>
        </div>
        {% endif %}
    </div>
    </section>

{% endblock content %}

purbeurre/products/templates/products/result.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% include 'products/base_product_title_img.html' %}
  
  <!-- Product Result Section -->
  <section id="product-result">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-12 text-center">
          <h2>Vous pouvez remplacer cet aliment par : </h2>
          {% if message %}
            <div class="alert alert-warning">{{message}}</div>
          {% endif %}
        </div>
        {% for substitute in object_list %}
          <div class="col-11 col-lg-4">
            <div class="product-thumb">
              <div class="nutriscore nutriscore-{{substitute.nutrition_grades|upper}} text-center"></div>
                <a href="{% url target substitute.id %}">
                  <img src="{{substitute.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
              <div class="product-thumb-legend">
                <div class="text-center">{{substitute|title}}</div>
                <div class="text-center">
                  <form action="{% url 'products:save' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input type="hidden" name="substitute_id" value="{{ substitute.id }}">
                    <button type="submit" class="btn btn-link"><i class="fas fa-save fa-1x"></i> Sauvegarder</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
</section>

{% endblock content %}

purbeurre/products/templates/products/search.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% include 'base_title_section.html' %}

  <!-- Product Result Section -->
  <section id="product-result">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-12 text-center">
          <h2>Choisissez votre produit actuel : </h2>
        </div>
        {% if not object_list %}
          <div class="alert alert-warning">Il n'y a pas de produits correspondant à {{title|title}}</div>
        {% endif %}
        {% for product in object_list %}
          <div class="col-12 col-lg-4">
            <div class="product-thumb">
              <div class="nutriscore nutriscore-{{product.nutrition_grades|upper}} text-center"></div>
                <a href="{% url target product.id %}">
                  <img src="{{product.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
                <div class="product-thumb-legend">
                  <p class="text-center">{{product|title}}</p>
                </div>
            </div>
          </div>
        {% endfor %}
        {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?query={{ query }}&page={{ page_obj.previous_page_number }}">Précédente</a>
                  {% endif %}
                  <span class="page-current">
                      Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?query={{ query }}&page={{ page_obj.next_page_number }}">Suivante</a>
                  {% endif %}
              </span>
          </div>
        {% endif %}
      </div>
    </div>
</section>

{% endblock content %}

purbeurre/products/templates/products/substitute_confirm_delete.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% include 'base_title_section.html' %}
    <section id="product-result">
      <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-4">
              <div class="product-thumb">
                <div class="nutriscore nutriscore-{{object.product_id.nutrition_grades|upper}} text-center"></div>
                <a href="{% url 'products:detail' object.product_id.id %}">
                  <img src="{{object.product_id.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
                <p class="text-center">{{object.product_id|title}}</p>
              </div>
            </div>
            <div class="col-1">
              <p><i class="fas fa-arrow-right fa-4x"></i></p>
            </div>
            <div class="col-4">
              <div class="product-thumb">
                <div class="nutriscore nutriscore-{{object.substitute_id.nutrition_grades|upper}} text-center"></div>
                <a href="{% url 'products:detail' object.substitute_id.id %}">
                  <img src="{{object.substitute_id.image_url}}" class="rounded mx-auto d-block" alt="">
                </a>
                <p class="text-center">{{object.substitute_id|title}}</p>
              </div>
            </div>
        </div>
        <div class="col-10 offset-1">
          <form method="post">{% csrf_token %}
            <p class="alert alert-warning">Vous êtes sur le point de supprimer ce substitut ?</p>
            <div class="text-center">
              <input type="submit" value="Valider" class="btn btn-lg btn-outline-secondary mx-3">
              <button onclick="window.history.back();" type="button" class="btn btn-lg btn-outline-secondary mx-3">Retour</button>
            </div>
          </form>
        </div>
      </div>
    </section>




{% endblock content %}