purbeurre/authentication/urls.py
# from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
# from .forms import AuthenticationFormEmail


app_name = 'authentication'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('modify/', views.ModifyView.as_view(), name='modify'),
]

purbeurre/products/urls.py
# from django.conf.urls import url

from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [

     path('search/', views.SearchView.as_view(), name='search'),
     path('<int:product_id>/result/', views.ResultView.as_view(), name='result'),
     path('save/', views.SaveView, name='save'),
     path('delete/<int:pk>', views.DeleteSubstituteView.as_view(), name='delete'),
     path('<int:pk>/detail/', views.DetailProductView.as_view(), name='detail'),
     path('myproducts/', views.MyProductsView.as_view(), name='myproducts'),
]

purbeurre/purbeurre/urls.py
from django.contrib import admin
from django.urls import path
# from django.conf import settings
from django.urls import include  # For django versions from 2.0 and up

from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('legal', TemplateView.as_view(template_name='legal.html'), name='legal'),
    path('products/', include('products.urls')),
    path('accounts/', include('authentication.urls')),
    path('admin/', admin.site.urls),
]

purbeurre/templates/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre - Du gras, oui, mais de qualité</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"> -->
  <!-- <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'> -->

  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">


  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/logo_pur_beurre-favicon.png' %}"/>

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}">
        <img src="{% static 'img/logo_pur_beurre.png' %}" id="nav-brand-img" alt="Brand">
        Pur Beurre
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
              <form action="{% url 'products:search' %}" method="get">
              <input name="query" class="form-control form-control-sm" id="navbar-input" type="text" placeholder="Rechercher">
            </form>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'authentication:account' %}" alt="Utilisateur"><i class="fas fa-user fa-2x"></i></a>
          </li>
          {% if user.is_active %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'products:myproducts' %}" alt="Mes produits"><i class="fas fa-carrot fa-2x"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'authentication:logout' %}" alt="Déconnexion"><i class="fas fa-sign-out-alt fa-2x"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  
  {% endblock %}

  <!-- Footer -->
  <footer class="py-3 bg-primary">
    <div class="container">
      <div class="row">
        <div class="text-center col-6"> <a href="{% url 'legal' %}">Mentions légales</a></div>
        <div class="text-center col-6">Contact</div>
      </div>
      
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/creative.min.js' %}"></script>

  <!-- Custom Front js -->
  <script src="{% static 'js/front.js' %}"></script>

</body>

</html>

purbeurre/templates/base_title_section.html
  <!-- Title Section -->
  <header id="user-name" class="bg-user-name">
    <div class="container-fluid h-200">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <h1 class="text-white font-weight-bold">{{ title|title }}</h1>
      </div>
    </div>
</header>

purbeurre/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui mais de qualité</h1>
          <h2 class="text-uppercase text-white font-weight-bold">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h1>
        </div>
        <div class="col-lg-8 align-self-baseline">
            <form action="{% url 'products:search' %}" method="get">
              <div class="input-group mb-3">
                <input name="query" type="text" class="form-control" placeholder="Rechercher un produit">
              <div class="input-group-append">
                <button class="btn btn-outline-secondary btn-light" type="submit">Chercher</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-black mt-0">Colette et Remy</h2>
          <hr class="divider my-4">
          <h3 class="text-black mt-0">De la ratatouille aux croissants</h2>
          <p class="text-black-50 mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille. </p>
          <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-12 order-1">
                  <p class="text-black-50 mb-4 text-justify"><strong>Colette Tatou</strong> : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
                </div>
                <div class="col-lg-6 col-12 order-3 order-lg-2">
                  <p class="text-black-50 mb-4 text-justify"><strong>Remy</strong> : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
                </div>
                <div class="col-lg-6 col-12 order-2 order-lg-3">
                  <img src="{% static 'img/colette-tatou-full.png' %}" alt="Colette">
                </div>
                <div class="col-lg-6 col-12 order-4">
                  <img src="{% static 'img/ratatouille-portrait.jpg' %}" alt="Remy">
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section bg-secondary" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous!</h2>
          <hr class="divider my-4">
          <p class="mb-5">Vous souhaitez partager votre avoir du bon gras avec nous, n'hésitez pas!</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+1 (202) 555-0149</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@yourwebsite.com">contact@yourwebsite.com</a>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

purbeurre/templates/legal.html
{% extends "base.html" %}

{% block content %}
  <!-- User name Section -->
  <header id="user-name" class="bg-user-name">
      <div class="container-fluid h-200">
        <div class="row h-100 align-items-center justify-content-center text-center">
          <h1 class="text-white font-weight-bold">Mentions légales</h1>
        </div>
      </div>
  </header>

  <!-- Mentions légales -->
  <section id="mentions-legales">
      <div class="container">
        <div class="row py-5 justify-content-center">
          <div class="col-md-8">
              <ul>
                <li>Créé avec <a href="https://www.djangoproject.com/" target="_blank">Django Framework</a></li>
                <li>Front-end template de <a href="https://startbootstrap.com/themes/creative/" target="_blank">Start Bootstrap</a></li>
                <li>Données issues de <a href="https://fr.openfoodfacts.org" target="_blank">OpenFoodFacts</a></li>
                <li>Image d'accueil de <a href="https://unsplash.com/photos/k60JspcBwKE" target="_blank">Kawin Harasai</a></li>
                <li>Images de Ratatouilles de <a href="https://www.pixar.com/feature-films/ratatouille" target="_blank">Pixar</a></li>
                <li>Icone de carrote de <a href="https://thenounproject.com/term/carrot/29691/" target="_blank">Fabien Jouin</a></li>
              </ul>
          </div>
        </div>
      </div>
  </section>
{% endblock content %}